"""Create table drive licenses

Revision ID: 03146163fafa
Revises: 8c7afaedcbaa
Create Date: 2023-05-04 16:25:47.224118

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '03146163fafa'
down_revision = '8c7afaedcbaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_licenses',
                    sa.Column('expiration_date', sa.Date(), nullable=False),
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('file_type', sa.String(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_licenses')
    # ### end Alembic commands ###
