"""Relationship One2Many user-branch

Revision ID: 035deeba3813
Revises: 2d146556266c
Create Date: 2023-05-15 19:33:54.770366

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '035deeba3813'
down_revision = '2d146556266c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    # ### end Alembic commands ###
