"""add branch id to vehicle

Revision ID: 1f0b259471a7
Revises: 335daf1261bc
Create Date: 2023-07-03 19:12:29.490943

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '1f0b259471a7'
down_revision = '335daf1261bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_vehicles_branch_id_branches', 'vehicles',
                          'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vehicles_branch_id_branches',
                       'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'branch_id')
    # ### end Alembic commands ###
