"""update_table_organizations

Revision ID: 21a62592bf2c
Revises: 9984d778a590
Create Date: 2023-09-20 16:26:30.369100

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '21a62592bf2c'
down_revision = '9984d778a590'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('branches_manager_id_fkey',
                       'branches', type_='foreignkey')
    op.drop_column('branches', 'manager_id')
    op.add_column('organizations', sa.Column(
        'manager_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column(
        'document_number', sa.String(length=20), nullable=True))
    op.create_foreign_key('organizations_manager_id_fkey',
                          'organizations', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organizations_manager_id_fkey',
                       'organizations', type_='foreignkey')
    op.drop_column('organizations', 'document_number')
    op.drop_column('organizations', 'manager_id')
    op.add_column('branches', sa.Column('manager_id', sa.UUID(),
                  autoincrement=False, nullable=False))
    op.create_foreign_key('branches_manager_id_fkey',
                          'branches', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###
