"""Update roles types

Revision ID: 2944a092e60a
Revises: 035deeba3813
Create Date: 2023-05-24 15:56:18.869989

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2944a092e60a'
down_revision = '035deeba3813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TYPE roleenum ADD VALUE 'driver'")
    op.execute("ALTER TYPE roleenum ADD VALUE 'provider'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
