"""Create table branches

Revision ID: 2d146556266c
Revises: 3e0d7a6e2bcc
Create Date: 2023-05-12 13:16:08.367975

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2d146556266c'
down_revision = '3e0d7a6e2bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('cost_center', sa.String(), nullable=False),
                    sa.Column('area', sa.String(), nullable=False),
                    sa.Column('purchase_order_sent_date',
                              sa.Date(), nullable=True),
                    sa.Column('manager_id', sa.UUID(), nullable=False),
                    sa.Column('organization_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['organization_id'], [
                                            'organizations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branches')
    # ### end Alembic commands ###
