"""create_sinisters_table

Revision ID: 335daf1261bc
Revises: 131d19158358
Create Date: 2023-06-13 11:21:04.119171

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '335daf1261bc'
down_revision = '131d19158358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sinisters',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('files_urls', sa.ARRAY(
                        sa.String()), nullable=True),
                    sa.Column('details', sa.String(), nullable=True),
                    sa.Column('vehicle_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sinisters')
    # ### end Alembic commands ###
