"""Crear tabla budget

Revision ID: 344cde01f5ba
Revises: 1f0b259471a7
Create Date: 2023-07-05 12:05:54.281810

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '344cde01f5ba'
down_revision = '1f0b259471a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
                    sa.Column('detail', sa.String(), nullable=False),
                    sa.Column('allocation_file', sa.String(), nullable=True),
                    sa.Column('amount', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('approval_date', sa.Date(), nullable=True),
                    sa.Column('approved', sa.Boolean(), nullable=False),
                    sa.Column('effective_until_date',
                              sa.Date(), nullable=False),
                    sa.Column('work_order_id', sa.UUID(), nullable=True),
                    sa.Column('vehicle_id', sa.UUID(), nullable=True),
                    sa.Column('organization_id', sa.UUID(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['organization_id'], [
                                            'organizations.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.ForeignKeyConstraint(
                        ['work_order_id'], ['work_orders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budgets')
    # ### end Alembic commands ###
