"""Create table organizations

Revision ID: 3e0d7a6e2bcc
Revises: 03146163fafa
Create Date: 2023-05-04 18:20:23.487083

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3e0d7a6e2bcc'
down_revision = '03146163fafa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('super_manager_id', sa.UUID(), nullable=False),
                    sa.Column('contact_id', sa.UUID(), nullable=False),
                    sa.Column('business_name', sa.String(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['super_manager_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
