"""Create table PO

Revision ID: 4c69b9f04a3e
Revises: 2944a092e60a
Create Date: 2023-06-01 18:06:39.074482

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4c69b9f04a3e'
down_revision = '2944a092e60a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
                    sa.Column('number', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('expires', sa.Boolean(), nullable=False),
                    sa.Column('due_date', sa.Date(), nullable=False),
                    sa.Column('file_path', sa.String(
                        length=255), nullable=False),
                    sa.Column('branch_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
