"""Create users table

Revision ID: 8c7afaedcbaa
Revises:
Create Date: 2023-04-24 17:39:18.434991

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8c7afaedcbaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('username', sa.String(
                        length=50), nullable=False),
                    sa.Column('password', sa.String(
                        length=60), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('phone', sa.String(length=25), nullable=True),
                    sa.Column('job', sa.String(length=25), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('role', sa.Enum('superadmin', 'admin', 'manager',
                                              'supermanager', 'agent', name='roleenum'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
