"""Add columns to vehicles

Revision ID: eade765d0120
Revises: 344cde01f5ba
Create Date: 2023-07-19 10:53:10.213119

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'eade765d0120'
down_revision = '344cde01f5ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fee', sa.Float(),
                  nullable=False, server_default='0.0'))
    op.add_column('vehicles', sa.Column('chassis', sa.String(
        length=30), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'chassis')
    op.drop_column('vehicles', 'fee')
    # ### end Alembic commands ###
