"""update_table_vehicles

Revision ID: f196abac44e0
Revises: 84e6fff65690
Create Date: 2023-09-27 17:16:23.974743

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f196abac44e0'
down_revision = '84e6fff65690'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column(
        'version', sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column('status', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('type', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('color', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'fuel_type', sa.String(length=20), nullable=True))
    op.add_column('vehicles', sa.Column('auth_documents_expiration_date', sa.Date(),
                                        nullable=True))
    op.add_column('vehicles', sa.Column(
        'ruta_expiration_date', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'ensurance_expiration_date', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'engraved_parts_date', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'title_file', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'auth_id_card_file', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'census', sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column('armor', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'telemetry', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'leasing', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('hooked', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'assistance', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'ensurance_company', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'franchise_deductible', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'policy_url', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('coverage_type',
                  sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column('purchase_type',
                  sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column(
        'ownership', sa.String(length=30), nullable=True))
    op.add_column('vehicles', sa.Column(
        'purchase_date', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('purchase_value', sa.Numeric(precision=10, scale=2),
                                        nullable=True))
    op.add_column('vehicles', sa.Column('vehicle_value', sa.Numeric(precision=10, scale=2),
                                        nullable=True))
    op.add_column('vehicles', sa.Column(
        'invoice_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'broker_name', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'ensurance_name', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'tire_measure', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column(
        'engine', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'engine')
    op.drop_column('vehicles', 'tire_measure')
    op.drop_column('vehicles', 'ensurance_name')
    op.drop_column('vehicles', 'broker_name')
    op.drop_column('vehicles', 'invoice_number')
    op.drop_column('vehicles', 'vehicle_value')
    op.drop_column('vehicles', 'purchase_value')
    op.drop_column('vehicles', 'purchase_date')
    op.drop_column('vehicles', 'ownership')
    op.drop_column('vehicles', 'purchase_type')
    op.drop_column('vehicles', 'coverage_type')
    op.drop_column('vehicles', 'policy_url')
    op.drop_column('vehicles', 'franchise_deductible')
    op.drop_column('vehicles', 'ensurance_company')
    op.drop_column('vehicles', 'assistance')
    op.drop_column('vehicles', 'hooked')
    op.drop_column('vehicles', 'leasing')
    op.drop_column('vehicles', 'telemetry')
    op.drop_column('vehicles', 'armor')
    op.drop_column('vehicles', 'census')
    op.drop_column('vehicles', 'auth_id_card_file')
    op.drop_column('vehicles', 'title_file')
    op.drop_column('vehicles', 'engraved_parts_date')
    op.drop_column('vehicles', 'ensurance_expiration_date')
    op.drop_column('vehicles', 'ruta_expiration_date')
    op.drop_column('vehicles', 'auth_documents_expiration_date')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'color')
    op.drop_column('vehicles', 'type')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'version')
    # ### end Alembic commands ###
