"""create_table_requests

Revision ID: ff7c393d73b4
Revises: b4075e0d994e
Create Date: 2023-07-26 11:23:11.641616

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ff7c393d73b4'
down_revision = 'b4075e0d994e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
                    sa.Column('type', sa.Enum('PRE', 'COR', 'VER',
                              'GOM', name='requesttypeenum'), nullable=False),
                    sa.Column('status', sa.Enum(
                        'DEFAULT', name='requeststatusenum'), nullable=False),
                    sa.Column('details', sa.String(), nullable=True),
                    sa.Column('odometer', sa.Integer(), nullable=False),
                    sa.Column('appointment_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('alternative_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('emergency', sa.Boolean(), nullable=True),
                    sa.Column('tire_quantity', sa.Integer(), nullable=True),
                    sa.Column('tire_brand', sa.String(), nullable=True),
                    sa.Column('tire_alternative_brand',
                              sa.String(), nullable=True),
                    sa.Column('tire_measure', sa.String(), nullable=True),
                    sa.Column('tire_reason', sa.Enum('DES', 'KMS',
                                                     name='requesttirereasonenum'), nullable=False),
                    sa.Column('tire_image', sa.String(), nullable=True),
                    sa.Column('zone', sa.String(), nullable=True),
                    sa.Column('user_validation', sa.Boolean(), nullable=True),
                    sa.Column('verification_type', sa.Enum('VTV', 'POL', 'AUT',
                                                           'CRI', name='requestvertypeenum'), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('vehicle_id', sa.UUID(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
